### ISSUE TITLE
Accepted Rule

### ISSUE THREAD

**Issue by nirgendswo** [vlucas/valitron#101]
There is a little Problem with the "accepted"-Rule. If i wan't that the accepted rule work, i have to set to the field also the "required"-rule. The Problem is that in the function Validate a field have not to be empty, except the field has a "required"-rule. 

I have change your code at line 752,

``` PHP
if (($v['rule'] !== 'required' && !$this->hasRule('required', $field) && (!isset($value) || $value === '')) && !$this->hasRule('accepted', $field)) {
  continue;
}
```

**Comment by chrisvanpatten** [comment]
I've also noticed this issue. It's a bit of a minor annoyance, as it means you'll get two messages when the validation fails—"Field is required" and "Field must be accepted"—which is a bit redundant. Not a huge deal, and not terribly hard to work around, but still an issue.

**Comment by willemwollebrants** [comment]
Guess what: I finally fixed this 🙂
Sorry it took quite so long
