### ISSUE TITLE
wrong integer validation 

### ISSUE THREAD

**Issue by silviucpp** [vlucas/valitron#113]
Hello when I validate a filed as beeing integer, I'm expecting to return false in case it's "123" because internally this is a string. 

Instead using  return filter_var($value, \FILTER_VALIDATE_INT) !== false; I think better to use is_int .

**Comment by piotr-cz** [comment]
Lately it's more common to use JSON then form to interchange data.
I've prepared such simple rule, I think it could be implemented in library

```php
// Define type rule
Valitron\Validator::addRule('type', function($field, $value, array $params) {
    return gettype($field) === $params[0];
}, 'Invalid type');

// Use
$v->rule(['type', 'integer'], 'quantity');
```
