### ISSUE TITLE
Allow re-use of validation rules and storage

### ISSUE THREAD

**Issue by mrclay** [vlucas/valitron#124]
Requiring to set the data in the constructor is an odd choice that removes the ability to validate several values with the same rules (user has to config a new object each time). Simple fix: add `setData()`.

As it is, storing data in the object makes this not a validator but a sort of validating-container hybrid; I can't just serialize this and store it somewhere without also storing the data.

Moving the static state to object state would also help there.

**Comment by nebulousGirl** [comment]
Alternatively, it could also be passed as a parameter to the validate method.

**Comment by willemwollebrants** [comment]
This is - finally - being worked on. See #108
