### ISSUE TITLE
Length rule

### ISSUE THREAD

**Issue by danielfpedro** [vlucas/valitron#127]
->rule('length', 'phone', 12]);

The phone have to be 12 longer but on message you say "must be longer than 12".

Is this right?

**Comment by laverboy** [comment]
I think this would be better as "must be longer than (n-1)"

**Comment by paxperscientiam** [comment]
@laverboy "must be at least 12 long" is not correct though, is it? Shouldn't be "must be **exactly** 12 long"?

**Comment by laverboy** [comment]
@paxperscientiam you are correct. Someone else spotted it though and it has been subsequently updated with this commit https://github.com/vlucas/valitron/pull/153. 

Thanks for pointing it out though.
