### ISSUE TITLE
If required is not set, empty field is not validated if needed

### ISSUE THREAD

**Issue by MaJerle** [vlucas/valitron#136]
Hi,

in validate() function is if statement which removes validation if there is not "required" field set on it as one of many rules.

Imagine that:
Using REST, user can update something database and on update, (for example) element_name is not required field. BUT, if users uses it as parameter to update, its length must be at least 5 characters.

Using this library, this is now not possible. 2 issues are:
1. I need to set "required" and if user don't want to update it, error is thrown,
2. If I don't set "required" and parameter is empty {"element_name":""}, validation will pass even if I set lengthMin to 5.

This should be fixed in validate() function.

**Comment by vlucas** [comment]
Can you provide a code example for what you mean? Fields don't have to be required to be validated.

**Comment by MaJerle** [comment]
You are right, then don't need to be.
The problem is, when field is not required but is passed as empty (code below)...

$data = [
'field' => ''
];

you will ignore other validation rules.

I have like this:

//Set rules
$v->rule('required', 'category_name')->message(__('Name is required!'))
->rule('lengthMin', 'category_name', 2)->message(__('Name size is too small!'));

And this will require that "category_name" field is in data array and its size is at least 2 characters.

But this:
//Set rules
$v->rule('lengthMin', 'category_name', 2)->message(__('Name size is too small!'));

will work ONLY, if "category_name" is in data array and its size is MORE THAN 0 chracters. If I pass this...
$data = [
'field' => ''
];

..validation will pass, which is NOT true.

Validation should pass in the second case in 2 possible cases:
1. "category_name" field does not exists in data array,
2. "category_name" field is greater than 2 characters.

I hope I was understandable.

**Comment by MaJerle** [comment]
I have fixed this using some modification in validate() function.

On "if" statement inside validate() function, I've changed === '' to === false and now works the same I want and as it is expected behaviour.

**Comment by vlucas** [comment]
Yes, thank you for explaining this. I will write a test for this to fix it.

**Comment by vlucas** [comment]
After thinking about this a little more and looking at the code, I think this is expected behavior. The main reason is that if your input source is `$_GET` or `$_POST` data, ALL fields on the page will be submitted. If they are not required, that's essentially saying it's OK if they are empty. Therefore, no validation needs to be done. If makes no sense to run length validations, etc. on a field that is optional, and left blank. It would be very confusing to the user to get errors about an empty field that was optional in the first place.

**Comment by MaJerle** [comment]
For me, required means that key must be in array, doesnt care if empty or
not. NotEmpty would mean that if it is there, then must not be empty.

And yes, if you use a form with get/post method.
Im using RESTFUL API where user sends data which he wants to update, so I
have to validate them only if they exists in array. Otherwise they are OK
if no required field exists.
24. nov. 2015 6:32 pop. je oseba "Vance Lucas" <notifications@github.com>
napisala:

**Comment by vlucas** [comment]
Even if you use a REST API and serialize a form, the keys are still going to be in there with empty values. You might try running your data through `array_filter` before validating it?

**Comment by MaJerle** [comment]
No,

I don't serialize a form, because data are sent from python program.
Only data, which should be updated are sent.

If I use array_filter and other things before, then 2 things happens:
1. User don't know that field, which was passed as '' is not updated.
2. User does not receive ERROR message that he send wrong data.

And again, if user don't want to update field, he just don't sent it. If he
sends it, then validation must be done on this field even if 'required' is
not set, and its value is ''.

Again, use of all this, I can do my own validation lib which is not my key
here.
Just wanna make your lib even better as it is.
ᐧ

--
Tilen Majerle
Tušev Dol 11
8340 Črnomelj
Slovenia
www: http://majerle.eu
e-mail: tilen@majerle.eu
skype: tjuln10

2015-11-24 21:36 GMT+01:00 Vance Lucas <notifications@github.com>:

**Comment by vlucas** [comment]
@MaJerle I get what you're saying, but the vast majority of users who have this library as a dependency are counting on the behavior. It would be a breaking change for nearly everyone using Valitron right now.

My point is that from Valitron's standpoint, sending a key with an empty value is the same as not sending the key at all. There is the possibility that this could be different, but since it's a breaking change, it would have to be done with an option or a flag, and can't be the default behavior.

**Comment by MaJerle** [comment]
That's great that you understand.

What about thinking 'optional' parameter instead of 'required'. If you set
field to 'optional' then if it is not passed, you just ignore rules, if it
is passed (no matter if empty or not) then you check other rules?
That seems logical then.

But this was looks like problem from start with lib design.
ᐧ

--
Tilen Majerle
Tušev Dol 11
8340 Črnomelj
Slovenia
www: http://majerle.eu
e-mail: tilen@majerle.eu
skype: tjuln10

2015-11-24 23:20 GMT+01:00 Vance Lucas <notifications@github.com>:

**Comment by willemwollebrants** [comment]
PR accepted
