### ISSUE TITLE
bump up version

### ISSUE THREAD

**Issue by zonuexe** [vlucas/valitron#138]
According to [vlucas/valitron/tags](https://github.com/vlucas/valitron/tags), last version v1.2.3 is released just a year ago.
I have very hoped for stable versioned tag is committed!

HEAD(a06309ce75faf394cad7b7d9a5de4831103b4b8e) of valitron seems to work as expected in our service.

**Comment by jayhoytt** [comment]
Yah, is Composer still the preferred method for installing or should one rather be grabbing straight from GitHub?

**Comment by vlucas** [comment]
Just published a new version (v1.2.4).

**Comment by zonuexe** [comment]
:+1:
