### ISSUE TITLE
any of the given fields mandatory validation

### ISSUE THREAD

**Issue by TheRoadstar** [vlucas/valitron#144]
Hi there,

Is there any option to validate for mandatory for any of the fields given.

for eg : 

i have a form contains user contact number and email id.

in this, at-least one among contact_number or email_id should be filled. If both are left empty, then an error should show. else if any or both are filled then it should return true

can you help me on this

**Comment by Quy** [comment]
This should be doable with the 'optional' validation if the contact_number and email_id will never be the same. Make both fields optional and apply the `different` rule.

**Comment by hlecuyer** [comment]
I have the same issue. But your solution doesn't work if both fields are empty. The rule `different` wouldn't apply then.

**Comment by willemwollebrants** [comment]
Indeed, if they both are empty you'll need to get a bit ... creative

There is at the moment no way to force validation of empty fields. I have a solution that involves adding an array to the data array: https://gist.github.com/willemwollebrants/e50813819ad9cc52168c
