### ISSUE TITLE
Alternate syntax - rules() - doesn't seem to work

### ISSUE THREAD

**Issue by amodef** [vlucas/valitron#148]
Hi guys,

I've tried to use the alternate syntax

    $data = ['foo' => ''];
    $rules = [ 'required' => 'foo'];
    $v = new Validator($data);
    $v->rules($rules);
    return $v->validate();
but it always returns true.

Using the "standard" syntax works well.

**Comment by amodef** [comment]
[Here is a bit more info about this possible bug.](https://gist.github.com/amodef/e61fa7e3131175a707ea)

It looks like if any of the rules is verified, it always return true... Is this an intended behaviour ?

**Comment by willemwollebrants** [comment]
I think you have an error in line 16-17 of your example:

$rules = ['required' => 'foo'];
$rules = ['required' => 'baz'];

You overwrite $rules in the second line, which means that there is no rule for the 'foo'-field. So Valitron just looks at the  'baz'-field, sees that it there and returns true.

Take a look at https://github.com/vlucas/valitron#alternate-syntax-for-adding-rules and let me know if that makes it a bit clearer :)

Ps: I also tried the example you posted here, and it looks like it return false (as it should)
