### ISSUE TITLE
version 39eaf82

### ISSUE THREAD

**Issue by Stunt** [vlucas/valitron#150]
Are you going to version this commit : @39eaf82 ?

**Comment by willemwollebrants** [comment]
I want to push out a new release as soon as possible, but since I only just (pretty) recently took on part of the maintenance for the package I would need to make some more time to adjust any bugs that still need fixing. I hope you understand :) 

But yes, a new release is in the works, coming soon

**Comment by willemwollebrants** [comment]
And here it is :)
