### ISSUE TITLE
How I can validate a file?

### ISSUE THREAD

**Issue by giwrgos88** [vlucas/valitron#157]
Hello, I saw on the documentation that there is not any option for validating files like size type etc. Does anyone knows if there is a way to validate a file?

Thanks

**Comment by willemwollebrants** [comment]
I think what you want to do is validate certain properties of a file. So for Valitron you should prepare an array of the properties you want to check (mimetype, filesize, ...) and validate that.
For example:
```php
//let's pretend we got this from $_FILES
$file = [
    'name'=>'filename.jpg',
    'type'=>'image/jpeg',
    'tmp_name'=>'/tmp/randomName',
    'error'=>0,
    'size'=>80000
];

$val = new \Valitron\Validator($file);

//make sure we have no error
$val->rule('equals', 'error', 0);

//check the mime type
$val->rule('in', 'type', ['image/jpeg', 'image/pjpeg']);

//check maximum file size
$val->rule('max', 'size', 50000);
```

**Comment by nebulousGirl** [comment]
You can also create custom rules that verify a UploadedFile object.

**Comment by madsem** [comment]
This doesn't work with multiple files sadly.

The error check just won't work no matter what I try.
'''php
// make sure no error happened
        $f->rule('equals', [
            'hero.error',
            'logo.error',
            'screenshot.error',
        ], 0)->message('{field} must have image selected');
```

The 'in' validation does work
```php
$f->rule('in', [
            'hero.type',
            'logo.type',
            'screenshot.type',
        ], $mimeTypes, true)->message('Wrong file type for {field}, only JPG, GIF & PNG are allowed.');
```

**Comment by willemwollebrants** [comment]
If you use the $_FILES array provided by php, the structure is different.
I think you are trying to validate a structure that looks like this (grouped per uploaded file):
```php
$_FILES = [
    'hero' => [
        'name' => 'filename.jpg',
        'type' => 'image/jpeg',
        'tmp_name' => '/tmp/randomName',
        'error' => 0,
        'size' => 80000

    ],
    'logo' => [
        'name' => 'filename.png',
        'type' => 'image/pngg',
        'tmp_name' => '/tmp/otherRandomName',
        'error' => 0,
        'size' => 4000
    ]
];
```
But the $_FILES array looks more like this (grouped by index):
```php

$_FILES = [
    'name' => [
        'hero' => 'filename.jpg',
        'logo' => 'filename.png',
    ],
    'type' => [
        'hero' => 'image/jpeg',
        'logo' => 'image/png',
    ],
    'tmp_name' => [
        'hero' => '/tmp/randomName',
        'logo' => '/tmp/otherRandomName',
    ],
    'error' => [
        'hero' => '0',
        'logo' => '0',
    ],
    'size' => [
        'hero' => '80000',
        'logo' => '4000',
    ]
];
```

This means that instead of validating the field 'hero.error', you probably want to validate the field 'error.hero' etc.

**Comment by madsem** [comment]
@willemwollebrants thanks a lot for your reply!

Actually, the structure of the $_FILES array looks like this:

```php
array:3 [▼
  "hero" => array:5 [▼
    "name" => "sdfkjdsfdsjflsd34401440 (1).jpg"
    "type" => "image/jpeg"
    "tmp_name" => "/tmp/phptk44mW"
    "error" => 0
    "size" => 1347201
  ]
  "logo" => array:5 [▼
    "name" => "sdfkjdsfdsjflsd34401440 (1).jpg"
    "type" => "image/jpeg"
    "tmp_name" => "/tmp/phpfGGX9q"
    "error" => 0
    "size" => 1347201
  ]
  "screenshot" => array:5 [▼
    "name" => "sdfkjdsfdsjflsd34401440 (1).jpg"
    "type" => "image/jpeg"
    "tmp_name" => "/tmp/phpJ9RhXV"
    "error" => 0
    "size" => 1347201
  ]
]
```

I'm using the same structure as in the 'in" validation, which works beautifully:
```php
$f->rule('in', [
            'hero.type',
            'logo.type',
            'screenshot.type',
        ], $mimeTypes, true)->message('Wrong file type for {field}, only JPG, GIF & PNG are allowed.');
```

This, doesn't:
```php
$f->rule('equals', [
            'hero.error',
            'logo.error',
            'screenshot.error',
        ], 0)->message('{field} must have image selected');
```

Also tried using 'notIn' which also didn't work.

**Comment by willemwollebrants** [comment]
Looks I misread your question quite a bit 😐
Your problem is caused by the 'equals' validator. The name is a bit misleading: it validates that the value of one field **matches the value of another field**. You could read it as 'the value of field must be equal to the value of this other field in the data-array. 

For matching a given value, you're going to have to use the 'in' validator:
```php
$f->rule('in', [
            'hero.error',
            'logo.error',
            'screenshot.error',
        ], [0])->message('{field} must have image selected');
```

I'm considering changing the behavior of 'equals' in v2.0. 'equals' should probably match a value, while this behavior is more of a 'sameAs' rule.

**Comment by madsem** [comment]
Hey @willemwollebrants that makes a lot of sense now that I'm looking at it with fresh eyes :)
I was thrown off because you also used 'equals' in your example above on the error field:
```php
//make sure we have no error
$val->rule('equals', 'error', 0);
```

But I agree, 'sameAs' / 'notSameAs' would be a lot more logical and 'equals' for equality comparison.
