### ISSUE TITLE
All fails except one

### ISSUE THREAD

**Issue by tmblog** [vlucas/valitron#162]
Why does all the rules fail except this, I pass an empty form with only 4 letters for a username.
```

$v = new Valitron\Validator($_POST);
$v->rule('alphaNum', 'username')->message('{field} can only contains letter and numbers.')->label('Username');
$v->rule('lengthMin', 'username', 5)->message('{field} must be a minimum of 5 letters.')->label('Username');
$v->rule('email', 'uemail')->message('{field} must be valid.')->label('Email');
$v->rule('lengthMin', 'password', 5)->message('{field} must contain minimum 5 characters')->label('Password');
$v->rule('equals', 'repass', 'password')->message('{field} must match your password')->label('Confirm Password');
```
Only the username is being validated, if the username is OK then the rest passes. What am I missing?

**Comment by willemwollebrants** [comment]
Can you show me an example of what data for $_POST should fail but doesn't?

**Comment by tmblog** [comment]
I'm trying with an empty array, previously I had all required but that seems pointless if it's matching lengthMin 5 (password).

**Comment by willemwollebrants** [comment]
That's probably why you're having trouble: Valitron only runs the validation for fields that are set and not empty. If you a field is required, it should be explicitly specified as 'required'.

**Comment by tmblog** [comment]
OK that makes sense, wouldn't it be more intuitive to assume it's required if is expecting lengthMin 5 or any type of validation? 

So to validate it, it must be required?
Thanks for the replies btw!

**Comment by willemwollebrants** [comment]
To validate it, it must be defined in the array and not null or empty (except for 'required'). 

What's more intuitive is a bit of a philosophical question really. I see the valitron-object as something that has "rules for elements in an array", not "rules for an entire array", if that makes sense. It tells us what each element of the array should be like, but not necessarily what the input array as a whole should be.

To be exact, there are 3 scenario's:
- normal: only validates the field if it's not null or empty
- optional: `$v->rule('optional', 'fieldname')` : if the element is set in the array, it must pass validation (even if it's null or empty)
- required: `$v->rule('optional', 'required')` : the element must be set, and not be null or empty
