### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by piernik** [vlucas/valitron#165]
I've downloaded 1.1.7 version with composer.
In lang folder there is no polish language, even though I see it on github - why?

**Comment by nebulousGirl** [comment]
The latest version is 1.2.5. You should try this one instead.

**Comment by piernik** [comment]
1.1.7 was automagically downloaded by composer.

**Comment by nebulousGirl** [comment]
Might be because some other package requires a lower version of composer. You can always trick composer with `"vlucas/valitron": "^1.2.5 as 1.1.7"`

**Comment by willemwollebrants** [comment]
As @nebulousGirl pointed out, it's generally recommended to use the most recent version on packagist. The polish language file was added in v1.2.4

If this happened when you installed it yourself (`composer require vlucas/valitron`) you may want to update composer and clear its cache:
```
composer self-update
composer clear-cache
```
