### ISSUE TITLE
Validator::rule() phpDoc type for $fields parameter should be "mixed"

### ISSUE THREAD

**Issue by ArtemGoutsoul** [vlucas/valitron#172]
phpDocfor this parameter should be modified to be "mixed" or "array|string" instead of "array".

It's clear that rule() accepts a single value as well as an array for the $fields parameter, since it's cast to array later on. The way it is now, some tools that parse phpDoc complain when you call it like this: `$v->rule('lengthMax', 'somefield', 200);` even though it's a perfectly valid way to do it.

```php
 /**
     * Convenience method to add a single validation rule
     *
     * @param  string                    $rule
     * @param  array                     $fields
     * @return $this
     * @throws \InvalidArgumentException
     */
    public function rule($rule, $fields)
...
        $this->_validations[] = array(
            'rule' => $rule,
            'fields' => (array) $fields,
            'params' => (array) $params,
            'message' => '{field} ' . $message
        );
```

**Comment by willemwollebrants** [comment]
Fixed thanks to @EgorGruzdev in pr #173
