### ISSUE TITLE
Alternative Rule Syntax?

### ISSUE THREAD

**Issue by Padrio** [vlucas/valitron#174]
Instead of the current array-notation syntax: 
```php
$rules = [
    'required' => 'foo',
    'accepted' => 'bar',
    'integer' => 'bar'
];
```

I would prefer to use a syntax like Zend and Laravel have them:

```php
$rules = [
    'foo' => 'required',
    'bar' => ['accepted', 'integer'],
];
```
Is there any way to accomplish this?

**Comment by willemwollebrants** [comment]
There isn't any way to do this with just Valitron at the moment, afaik. But especially for you* I made this helper class (It will probably be in the next release if I can come up with a decent name for it):
```php
class ValitronFieldRules extends \ArrayObject
{
    public function __construct(array $fields)
    {
        array_map(function ($field) use ($fields) {
            //Loop through all rules for the given field
            array_map(function ($rule) use ($field) {
                //Rule must be an array
                $rule = (array)$rule;
                //First element is the name of the rule
                $rule_name = array_shift($rule);
                //Add the field and additional parameters to the rule
                $this[$rule_name][] = array_merge([$field], $rule);
            }, (array)$fields[$field]);
        }, array_keys($fields));
    }
}
```
You use it like this:
```php
$v = new \Valitron\Validator([]);
$v->rules((array) new ValitronFieldRules([
    'foo' => ['required', ['lengthMin', 4]]
]));
```

Don't use it in the constructor, that won't work (for now). 
*it's also pretty useful for myself :)

**Comment by Padrio** [comment]
Awesome! Thanks

**Comment by Padrio** [comment]
Reopened this one, so you dont foget to add this into the next release! ;)

**Comment by joseph-montanez** [comment]
I've went a bit further and use a different method. For Example:

    $rules = [
        'First_Name' => [
            'label' => 'first name',
        ],
    ];

If only a label is provided the it is assumed that its a required field. If you need to customize the error message then:

    $rules = [
        'Address' => [
            'label' => 'address',
            'messages' => [
                'required' => 'Please enter an {field} before saving.',
            ]
        ],
    ];

Rules with parameters:

    $born_before = new DateTime('1900-01-01');
    $born_after = new DateTime();
    $born_after->add(new DateInterval('P1Y')); //-- Max 1 year from now
    $rules = [
        'DOB' => [
            'label' => 'date of birth',
            'rules' => [
                ['dateBefore', $born_after],
                ['dateAfter', $born_before],
            ],
            'messages' => [
                'dateBefore' => 'The {field} must not be before ' . $born_after->format('F j, Y'),
                'dateAfter' => 'The {field} must not be after ' . $born_before->format('F j, Y'),
            ]
        ]
    ];

by using an array I can easily add in validation dependency:

    if ($traveler['Age'] < 16) {
        $rules['Weight'] = [
            'label' => 'weight',
            'rules' => [
                ['required'],
                ['integer'],
                ['min', 0],
                ['max', 1000],
            ],
            'messages' => [
                'integer' => 'The {field} must be a number',
                'min' => 'The {field} must be after {field1}',
                'max' => 'The {field} must be before {field1}',
            ],
        ];
    }

However, I just extend the validator class: https://gist.github.com/joseph-montanez/32c6293b0983e6c67713f9deb19ec61b

This lets me the do the following:
	$v = new Validator($traveler);
	$v->setDefaultRequireMessage('Please enter a {field} before saving.');

	$rules = [/* ... */];
	
	$v->mapRules($rules);

	$valid = $v->validate();
	$errors = $v->firstErrors();

It does seem better to just allow for different types of parses with one standard array syntax to morph into. This way it can be replaced with JSON, YAML, XML, etc and those can be converted to the generic array syntax.

**Comment by willemwollebrants** [comment]
That's a nice way of adding rules to a field. I like the word "map" for this concept and may have to steal it :)

For JSON, YAML etc: I think it's better for Valitron to have one good way to map rules (an array seems appropriate). There are already plenty of ways to parse other formats and convert them to an array.  Parsers for specific formats could be additional packages that can be recommended when installing.

**Comment by the94air** [comment]
I think you should add these enhancements really fast.  because it is insane and super easy.

**Comment by willemwollebrants** [comment]
The best way to get enhancements really fast is to send a pr ;)

Not for this, because [I just merged it](https://github.com/vlucas/valitron/pull/183)

```php
$rules = array(
    'myField1' => array(
        'required',
        array('lengthMin', 3, 'message' => 'Must be 3 characters long')
    ),
    'myField2' => array(
        'required',
        array('lengthMin', 4, 'message' => 'Must be 4 characters long')
    )
);

$v = new Validator(array(
    'myField1' => 'foo',
    'myField2' => 'bar',
));

$v->mapFieldsRules($rules);
```

This will be in the next release (and is a great way of adding rules)
