### ISSUE TITLE
Custom date rules not working for me

### ISSUE THREAD

**Issue by the94air** [vlucas/valitron#177]
I am trying to add this new rule
```
$v->rule('realDate',['year', 'month', 'day']);
```
I tried to add the rule `date` in my php validation but when i add the date (2017-2-31) witch does not exists in the real date the validation passed (VERY BAD)
so am trying to use the php function [checkdate](http://php.net/manual/en/function.checkdate.php). It returns true/false and it is better than useing preg_match way.
I have build a custom rule but it is not working? and also not giving any errors
```
Validator::addRule('realDate', function($field, $value, array $params, array $fields) {
// ^^^^^--should i use the Validator
	$year = $params[0]; $month = $params[1]; $day = $params[2];

	if (checkdate($Validator->_fields[$month], $Validator->_fields[$day],//  $Validator->_fields[$year]) === false) {
		return false;
	}
}, 'This is not valid date.');

$v = new Validator($_POST);
// lets say the posted data $_POST['year'], $_POST['month'], $_POST['day']
$v->rule('realDate',['year', 'month', 'day']);
```

**Comment by willemwollebrants** [comment]
It seems to me there is are quite a few things that need explaining.

First of all, the *date* rule checks if the value provided can be converted by strtotime. For your case:
```php
echo date('Y-m-d', strtotime('2017-2-31'));

// outputs 2017-03-03, so March 3rd.
```


Second of all, adding custom rules using Validator::addRule. The basic syntax is as follows:
 
```php
\Valitron\Validator::addRule('realDate', function($field, $value, array $params, array $fields){
// $field is the name of the field being tested
// $value is the value of the field being tested
// $params is an array with additional parameters (like the return from func_get_args());
// $fields is an array with all field=>value pairs for the current Validator.
});
```
(You can always use print_r or var_dump if you're unsure what a parameter holds.) 

So here's  what we need to do to support checkdate when we have 3 fields:

First step is to create the rule:

```php
\Valitron\Validator::addRule('realDate', function ($field, $value, array $params, array $fields) {

    //get the name of all fields. This probably needs some checking for missing values etc.
    $dayField = $params[0][0];     // 'day'
    $monthField = $params[0][1];   // 'month'
    $yearField = $params[0][2];    // 'year'


    //get all values. This also probably needs some checking for missing values etc.
    $day = $fields[$dayField];      // '31'
    $month = $fields[$monthField];  // '3'
    $year = $fields[$yearField];    // '2017'


    //finally, run the check
    return checkdate($month, $day, $year);

}, 'is not a valid date.');
```

And after that, we can use our rule:


```php

$exampleInput = ['day' =>'31', 'month' => '2', 'year' => '2017']; //could be $_POST

$v = new \Valitron\Validator($exampleInput);

/*
You only need to add the rule to one field.
You can add it to all fields too, but you probably only want the error to show up once
*/
$v->rule('realDate', ['day'], ['day', 'month', 'year']);


var_dump($v->validate()); // false

var_dump($v->errors()); // array(1) { ["day"]=> array(1) { [0]=> string(24) "Day is not a valid date." } }
```


There's a lot of info in this reply, so if anything is unclear feel free to let me know :)

**Comment by the94air** [comment]
The thing that make me confused is the $_POST data. And as i see in the validate.php i have used

`$Validator->_fields` and i needed to use `$fields` as a $_POST

and also i have to used `use Valitron\Validator;`

I tried the code and it was very help full thanks @willemwollebrants

**Comment by willemwollebrants** [comment]
`$Validator->_fields` will only be defined inside a Validator object, not in a callback. So if you add a rule, always get the values from `$fields`

**Comment by the94air** [comment]
I am having a problem with dateFormat, dateAfter and dateBefore rules 
`$v->rule('dateBefore', 'date', ['1937-1-1']);`

**Comment by willemwollebrants** [comment]
The 3th parameter should not be an array, but a strtotime-compatible string or a DateTime (I prefer DateTime's because it's a bit clearer)

```php
$v->rule('dateBefore', 'date', DateTime::createFromFormat('Y-m-d', '1937-1-1'))
```

**Comment by the94air** [comment]
Thanks man. I really appreciate that :+1:

**Comment by the94air** [comment]
The only thing has left is the error messages. Do you have a build in function to output error for each html input?

**Comment by the94air** [comment]
This is good right?
```
if($v->validate()) {
    echo "Yay! We're all good!";
} else {
    $errors = $v->errors();
}

function has_error($field) {
	global $errors;
	return isset($errors[$field][0]);
}

function first_error($field) {
	global $errors;
	echo $errors[$field][0];
}
```
And in the form
```
<div>
     <label for="username">Your username</label>
     <input type="text" name="username" id="username">
     <?php if (has_error('username')) { first_error('username'); } ?>
</div>
```
