### ISSUE TITLE
Add the ability to set the data for the validation by a setter method.

### ISSUE THREAD

**Issue by AchoArnold** [vlucas/valitron#184]
I would love to have valitron as a dependency on a class I'm working on. This would ensure that I can unit test the class without having to test valitron. eg

```php
class CustomValidator {
    private $valitronValidator;

    function __construct(Validator $validator)
    {
        $this->valitronValidator = $validator;
    }

    public function doSomething()
    {
        // TODO: Not yet available.
        $this->valitronValidator->setData(['name' => 'Arnold']);

        $this->valitronValidator->rules(['name' => 'string']);

        return $this->valitronValidator->validate();
    }
}
```

**Comment by willemwollebrants** [comment]
You can use the withData method:
```php
class CustomValidator
{
    private $valitronValidator;

    function __construct(Validator $validator)
    {
        $this->valitronValidator = $validator;
    }
    public function doSomething()
    {
        $validator = $this->valitronValidator->withData(['name' => 'Arnold']);
        $validator->rules(['name' => 'string']);
        return $validator->validate();
    }
}
```

**Comment by AchoArnold** [comment]
@willemwollebrants That is true indeed. I'm using this package with laravel which does some automatic dependency resolution. When it sees the `Validator` class as a dependency, It would attempt to create a instance for the `Validator` class and this would fail because It wouldn't know which `$data` to use when creating the new `Validator` instance. Of course there are workarounds to this but feel like the `data` parameter shouldn't be required int he constructor of this validator.

**Comment by willemwollebrants** [comment]
Merged your PR: thanks :)

I guess this should fix the problem.
