### ISSUE TITLE
Is there a way to verify that no extra field (other than the ones defined in rules) are present in the body?

### ISSUE THREAD

**Issue by divye01** [vlucas/valitron#189]

**Comment by willemwollebrants** [comment]
If I understand correctly what your asking: there's not a rule for this. But there is a way: the second parameter of the constructor takes an array with field names that will act as a filter. Using this and the data() method you can get what I think you want:
```php
$data = array(
    'foo' => 1,
    'bar' => 2
);
$val = new \Valitron\Validator($data, ['foo']);
$filtered = $val->data(); // array('foo'=>1)
```

Please not that this *will not add* keys that don't exist, it really is just a filter

**Comment by divye01** [comment]
Yeah, I was moreover looking for a check to see only the valid keys are present in the body. 
However, `array_diff_key($_REQUEST['body'], $rules)` will check the keys in the body and return the extra ones. (leaving it just in case anyone wonders)
