### ISSUE TITLE
custom validation

### ISSUE THREAD

**Issue by masterkamlesh** [vlucas/valitron#193]
i need to put validation on each combobox or dropdown to select element.
by default selected value is 0
so i need to validate they must select other than 0

**Comment by willemwollebrants** [comment]
You can check that the value is not zero:
```php
$validator = new \Valitron\Validator(['my_field'=>'0']);
$validator->rule('notIn', 'my_field', ['0'],true);
```
Or you can check if the value is one of the other keys in the combobox. This is a bit more defensive: it makes sure you have an actual, valid value.
```php
$validator = new \Valitron\Validator(['my_field'=>'0']);
$validator->rule('In', 'my_field', ['option_1', 'option_2', ... ],true);
```
Or you can create a custom validator rule:
```php
$validator->rule(function($value){
    return intval($value) != 0;
}, 'my_field')->message("{field} is not valid");
```
