### ISSUE TITLE
custom validation writting

### ISSUE THREAD

**Issue by masterkamlesh** [vlucas/valitron#194]
how do i write custom validation for

if(($membertype=='mother' && $sex=='m') || ($membertype=='father' && $sex=='f' ))
	{
		$msg.= "<li>Kindly Check Sex Of either Mother OR Father  ??  </li>";
			$focusId[]='male';
	}

**Comment by willemwollebrants** [comment]
You can do this [using a callback rule](https://github.com/vlucas/valitron#adding-custom-validation-rules).  The callback receives 4 parameters: the name of the field, the value being checked, an array of (optional) parameters and an array containing all the data that is being verified. Using that last parameter, you can get the value for another field and use it in your rule. Something like this:
```php
//create a validator with the data we need
$validator = new \Valitron\Validator([
    'memberType' => 'mother',
    'sex' => 'm'
]);

//add a custom rule
$validator->rule(function ($fieldName, $value, $parameters = [], $data = []) {
    //let's assume for now that $data['memberType'] is always set
    if ($data['memberType'] === 'mother' && $value === 'm' || $data['memberType'] === 'father' && $value === 'f') {
        return false;
    }

    return true;

}, 'sex')->message('Kindly check ...');

//run validations
$validator->validate(); // returns false
var_dump($validator->errors());  // field 'sex' gets the error message
```
