### ISSUE TITLE
PHP error in rules method

### ISSUE THREAD

**Issue by auroraeosrose** [vlucas/valitron#204]
array_unshift() expects parameter 1 to be array, string given
vendor\vlucas\valitron\src\Valitron\Validator.php:1202

Need to do an is_array check on the $innerParams before doing an array_unshift

probably just ignore the rule if it's improperly formatted?

$validator->rules(['required' => ['foo', 'bar']]); will cause the bug

**Comment by willemwollebrants** [comment]
I've decided to cast to an array instead of ignoring the rule, for 2 reasons:
- just ignoring malformed rules seems dangerous: you might think your validating, but the rule is not there
- the intent is pretty clear: we want to add a 'required' rule for these fields.

**Comment by auroraeosrose** [comment]
sounds good to me! thanks :)
