### ISSUE TITLE
Phone number validation?

### ISSUE THREAD

**Issue by kingsloi** [vlucas/valitron#207]
Does anyone have any recommendations about validating a phone number? I know they can be entered in 101 ways (country codes, area codes, +xx, +xx (0), (xxx) xxx-xxxx, xxx-xxx-xxxx, xxxxxxxxx, etc.)

My thoughts so far are to validate with regex and only allow for `0123456789, (), -, +`, with a minimum of 10 characters. Does that sound reasonable for all national/international numbers?

**Comment by willemwollebrants** [comment]
I would allow 'x' too: sometimes people will add enter something like +32 12 345 678 x99 where you need to dial the number and then enter their extension.

Phone numbers are hard :/ If you want to be sure and don't mind a bit of overhead, I'd use [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) which is a PHP version of Google's libphonenumber and hasn't failed me yet

**Comment by kingsloi** [comment]
hey @willemwollebrants, that's a great point, thank you! 

The difficult with the project I'm working on is that the audience is global for some sites, domestic for others, so it's hard to pick a specific style.

I think regex for those allowed characters, plus a minimum length is best. 

Thanks for your help!
