### ISSUE TITLE
Validation of required field that may be empty or null

### ISSUE THREAD

**Issue by ducsuus** [vlucas/valitron#208]
It would be useful to implement the ability to validate fields that are required, but may have empty or null values. 

I do not believe this is currently possible. The required rule will consider empty or null values to be invalid. The optional rule allows empty or null values to be validated with a custom rule, _but only_ if the field specified has been set. The two rules (of course) cannot be used in conjunction to achieved this desired behaviour.

Perhaps something similar to pull request #139 would be suitable?

**Comment by willemwollebrants** [comment]
Thanks for your suggestion. I've gone a bit of a different route, and added a parameter for the required rule. You can see my code in the [in this branch](https://github.com/vlucas/valitron/tree/iss208).

The parameter is a boolean, where true means that empty values ('', null) are also considered valid. The default is false, so the behavior we have now.

Example:
```php
//default behavior
$v = new Validator(array('foo'=>null, 'bar'=>''));
$v->rule('required', 'foo');
$v->rule('required', 'bar');
$v->validate() // returns false, both foo and bar are 'not set'
//with the new parameter
$v = new Validator(array('foo'=>null, 'bar'=>''));
$v->rule('required', 'foo', true);
$v->rule('required', 'bar', true);
$v->validate() // returns true, both foo and bar are empty, but still considered 'set'
```
Tbh, the code feels a bit hackey, so I'm going to sleep on it a little bit before merging it in.

**Comment by ducsuus** [comment]
Ah - good idea, I hadn't thought of that! This still allows the rule to be on a field by field basis.

Other than changing the behaviour for all fields being validated is there any other way to achieve this? Perhaps pass an array of values also accepted into the rule (so ['null'], etc)?

**Comment by willemwollebrants** [comment]
You mean like a flag for the entire Valitron instance? No, there isn't any. To be honest, I like to keep the rules self-contained if you know what I mean. When you're hunting a bug, it's easier to look at how the rule was defined as long as you can predict what the rule will be doing. 

Of course you can still pass an array of fields to the rule like this: 
```php
$v = new Validator(array('foo'=>null, 'bar'=>''));
$v->rule('required',array('foo', 'bar'), true);
```

Meanwhile, I found an edge-case: 0, '0' and false are also considered 'empty' now, but they shouldn't be. Will fix tomorrow morning :)

**Comment by willemwollebrants** [comment]
Well looks like I've finally gotten around to fixing this :)
