### ISSUE TITLE
Passing Object params to Custom Function Causes PHP Warning

### ISSUE THREAD

**Issue by it-all** [vlucas/valitron#216]
When passing an object in the $params argument of a custom validation function, if the custom validation fails, the following PHP Warning results:

Object of class {param class} could not be converted to string .../vendor/vlucas/valitron/src/Valitron/Validator.php line: 841

**Comment by willemwollebrants** [comment]
Odd. Can you provide some code?

**Comment by it-all** [comment]
`$this->validator::addRule('unique', function($field, $value, array $params, array $fields = []) {
            if (!$params[0][1]->errors($field)) {
                return !$params[0][0]->recordExistsForValue($value);
            }
            return true; // skip validation if there is already an error for the field
        }, 'Already exists.');

        foreach ($this->model->getUniqueColumns() as $databaseColumnModel) {
            $this->validator->rule('unique', $databaseColumnModel->getName(), [$databaseColumnModel, $this->validator]);
        }`

Note that my validator is a clone of the instance from:  `$this->validator = $this->validator->withData(..)`

**Comment by it-all** [comment]
Here's a clearer example:

`class TestObject{}
$object = new TestObject();

$validator::addRule('unique', function($field, $value, array $params, array $fields = []) {
            return false; // set false to test error condition
        }, 'Already exists.');

$validator->rule('unique', '{field}', [$object]);
$validator->validate()`

**Comment by it-all** [comment]
Sorry for the multiple posts. I've simplified it further:

```
$v = new \Valitron\Validator(['fieldname' => 'a']);
$v::addRule('unique', function($field, $value, array $params, array $fields = []) {
    return false; // return false to test error condition
}, 'Already exists.');

class TestObject{}
$object = new TestObject();

$v->rule('unique', 'fieldname', [$object]);
echo ($v->validate()) ? 'valid' : 'invalid';
```
results in "Catchable fatal error: Object of class TestObject could not be converted to string in .../vendor/vlucas/valitron/src/Valitron/Validator.php on line 844"

A side note, if 'fieldname' is set as '' ($v = new \Valitron\Validator(['fieldname' => '']);, the unique rule does not run. I don't understand why not.

**Comment by willemwollebrants** [comment]
The problem is, as you point out, with  array wrapping on this line :  
```php
$v->rule('unique', 'fieldname', [$object]);
```

you're not actually passing $object as a parameter, you're passing an array containing $object as the first parameter. The rule method uses the 1st parameter to determine the rule, the 2nd parameter to determine the field(s), and all the other parameters are added tot the parameters array.

So to pass more than one parameter, we simply do it like this:
```php
$v->rule('unique', 'fieldname', $object_1, $object_2, $object_3);
```

For example, the built-in _lengthBetween_ rule needs 2 parameters: a minimum and a maximum. We use it like this:
```php
$minimum = 0;
$maximum= 10;
$v->rule('lengthBetween', 'fieldname', $minimum, $maximum);
```

**Comment by it-all** [comment]
ahhh, thanks!!
