### ISSUE TITLE
TypeError in 1.4.1 if passing Eloquent 5.1 object

### ISSUE THREAD

**Issue by tflight** [vlucas/valitron#223]
I'm using Valitron to validate Eloquent (5.1) models. Until 1.4.1 I could pass the model itself to Validator, set my rules, and validate.

Since updating to 1.4.1, when validating an Eloquent object that includes a `'required'` rule, I get the following error.

> Argument 4 passed to Valitron\Validator::validateRequired() must be of the type array, object given

When I inspect, I can see the following is passed to `validateRequired`.

```
$field = "name" (4)
$value = "My Name" (7)
$params = array ()
$fields = App\Models\Objective
```

If I take out the `'required'` rule, everything works as it did in 1.4.0 and earlier. Or, I can leave the rule in and instead of passing the Eloquent model itself, I can use Eloquent's `toArray` method, which will also work and is an easy fix.

I'm not necessarily thinking this is a bug, but perhaps it is, or at least here is a workaround for anyone else who might find themselves in the same situation.

**Comment by tflight** [comment]
I've reduced this issue as much as I think I can. With the following composer.json

```json
{
    "require": {
        "vlucas/valitron": "1.4.1",
        "illuminate/database": "5.5.*"
    }
}
```
Then the following PHP

```php
<?php

require __DIR__ . '/vendor/autoload.php';

class Widget extends \Illuminate\Database\Eloquent\Model
{
}

$widget = new Widget;
$v = new Valitron\Validator($widget);
$v->rule('required', 'name');
echo ($v->validate()) ? "valid" : "invalid";
```
I get the following error.
```
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Valitron\Validator::validateRequired() must be of the type array, object given in /Users/tflight/Code/validator/vendor/vlucas/valitron/src/Valitron/
Validator.php:149
Stack trace:
#0 [internal function]: Valitron\Validator->validateRequired('name', NULL, Array, Object(Widget))
#1 /Users/tflight/Code/validator/vendor/vlucas/valitron/src/Valitron/Validator.php(977): call_user_func(Array, 'name', NULL, Array, Object(Widget))
#2 /Users/tflight/Code/validator/v.php(14): Valitron\Validator->validate()
#3 {main}
  thrown in /Users/tflight/Code/validator/vendor/vlucas/valitron/src/Valitron/Validator.php on line 149
```

This works fine if you instead require 1.4.0. It also works fine if you do not add the rule requiring the name. (No PHP error, will return valid or invalid appropriately.

**Comment by willemwollebrants** [comment]
Hm, I see what the problem is. The signature of validateRequired was indeed changed. I'll see if I can remove the constraint without causing other problems.

**Comment by willemwollebrants** [comment]
I've probably fixed it, and will push a new release soon (waiting on travis ci, they seem to be having some problems)

I must however tell you that valitron is meant to be used with arrays, not objects. Objects that implement the ArrayAccess interface (like Eloquent's Model class does) will probably work 90% of the time, but no guarantees :)

**Comment by tflight** [comment]
Thanks so much @willemwollebrants!
