### ISSUE TITLE
lengthMax warns about characters although there's no needed.

### ISSUE THREAD

**Issue by talovicnedim** [vlucas/valitron#236]
Here's the code:

```
$v = new v([
           'name' => 'John Doe',
            'email' => 'john.doe@gmail.com'
        ]);

$v->rule('required', ['name', 'email']);
$v->rule('lengthMax', ['name', 'email'], 50);

if ($v->validate()) {
      return 'Everything is valid.';
} else {
     print_r($v->errors());
}
```

As you can see, `name` and `email` are required and they mustn't exceed 50 characters. 

However, if API users pass the email only, it will return both errors. Why?

```
$v = new v([
     'email' => 'john.doe@gmail.com'
]);
```

Error:

```
Array
(
    [name] => Array
        (
            [0] => Name is required
            [1] => Name must not exceed 50 characters
        )

)
```
The name doesn't exist, so it couldn't exceed 50 characters. 

Shouldn't it only be `Name is required`? When a user sends the name, if there's less than 50 characters, then it can warn users.

**Comment by willemwollebrants** [comment]
This is expected behavior: when a field is required, all the rules will be checked. See #195
