### ISSUE TITLE
stream_resolve_include_path error on xampp windows installation

### ISSUE THREAD

**Issue by omarllorens** [vlucas/valitron#247]
Hi. We are using this library on our project, https://github.com/tsolucio/corebos , and never we had any problem with the **stream_resolve_include_path** function, I suppose, because normally we have all our installations in Linux servers.

But a few days a new customer had this problem on xampp windows installation.

**Fatal error:  Uncaught InvalidArgumentException: Fail to load language file 'include/validation/lang/es.php' in C:\xampp\htdocs\master\include\validation\Validator.php:107**

So, we replace temporally this function to file_exist on 107 line and now works. 

Have you had this problem before and you know how to solve it?
I would prefer not to modify the library so as not to have problems when updating.

Thanks!

**Comment by willemwollebrants** [comment]
I can't say I have had this problem before (also linux mostly). Google reveals that stream_resolve_include_path on windows has some caching issues and that a restart might be needed but I can imagine you've tried that already.

Digging through your code, [I see this ](https://github.com/tsolucio/corebos/blob/master/include/validation/load_validations.php#L29)
```php
parent::__construct($data, $fields, substr($current_language, 0, 2), 'include/validation/lang');
```
Can you try that without the `$langDir` parameter? Like so:
```php
parent::__construct($data, $fields, substr($current_language, 0, 2));
```
