### ISSUE TITLE
Boolean validation / Postman

### ISSUE THREAD

**Issue by Varin6** [vlucas/valitron#250]
I'm using JSON files for rules, so my validation files look like this:

```
{
  "required":[
    ["emailAddress"],
    ["password"],
    ["code"],
    ["authenticate"],
    ["rememberMe"]
  ],
  "email":[
    ["emailAddress"]
  ],
  "lengthMax":[
    ["emailAddress", 190],
    ["password", 100],
    ["code", 8]
  ],
  "lengthMin":[
    ["password", 6],
    ["code", 8]
  ],
  "boolean":[
    ["authenticate"],
    ["rememberMe"]
  ]
}
```

Now, I try to pass "false" or "true" in Postman, but still getting the error:

```
{
    "authenticate": [
        "Authenticate must be a boolean"
    ],
    "rememberMe": [
        "RememberMe must be a boolean"
    ]
}
```

Any idea what I might be doing wrong? I tried passing 1 and 0, same error shows up.

**Comment by willemwollebrants** [comment]
Are you sure you're passing the variables as a boolean (so not as string "true" or int 1)? Our boolean test is just a thin wrapper around php's built-in is_bool() function, so I'm guessing the problem is those variables get converted to string somewhere along the way.
