### ISSUE TITLE
Incorrect russion translate

### ISSUE THREAD

**Issue by pavelinside** [vlucas/valitron#252]
'equals'        => "должно содержать '%s'" ->   (должно БЫТЬ РАВНО '%s')
    'length'        => "должно быть длиннее, чем %d" -> (должно быть ДЛИНОЙ %d)
    'min'           => "должно быть больше, чем %s" -> (должно быть НЕ МЕНЕЕ, чем %s)
    'max'           => "должно быть меньше, чем %s" -> (должно быть НЕ БОЛЕЕ, чем %s)
    'lengthMin'     => "должно содержать более %d символов" -> (должно содержать НЕ МЕНЕЕ %d символов)
    'lengthMax'     => "должно содержать менее %d символов" -> (должно содержать НЕ БОЛЕЕ %d символов)

corrections are highlighted in capital letters; please fix this

**Comment by willemwollebrants** [comment]
Can you send a PR for this? You can do this by going to https://github.com/vlucas/valitron/blob/master/lang/ru.php and click on the little pencil at the top right.

My Russian is nonexistent, so if you could add this there it would things a lot easier :)

**Comment by pavelinside** [comment]
Yes, I fix
