### ISSUE TITLE
'In' Rule Not Setting Error Properly

### ISSUE THREAD

**Issue by it-all** [vlucas/valitron#254]
Hello! I'm trying to validate each element of an input array, roles, to be in another array, by calling
`$v->rule('in', 'roles.*, [1,2,3,4])`
But upon an invalid value the errors array contains 'roles.*' as the field instead of 'roles', so the error does not display on my form page. Am I doing something wrong or is this a bug?

**Comment by it-all** [comment]
This trick makes it work. I'm sure there's a better fix or way of making the rule call.
```
class ValitronValidatorExtension extends Validator
{
    public function error($field, $msg, array $params = array())
    {
        if (substr($field, mb_strlen($field) - 2, 2) == '.*') {
            $field = substr($field, 0, mb_strlen($field) - 2);
        }

        parent::error($field, $msg, $params);
    }
}

```

**Comment by willemwollebrants** [comment]
You're not doing anything wrong, it's a 'feature' :)

Like a lot of these things, it's a bit philosophical: the validation does not fail for 'rules', it fails for 'one of the items in rules'. You can either check if there is an error for 'rules.*' or use your solution which is pretty elegant.

**Comment by it-all** [comment]
Got you. Thanks!
