### ISSUE TITLE
Validation of array children always considered "required"?

### ISSUE THREAD

**Issue by ecker00** [vlucas/valitron#262]
The validator seems to behave differently when validating a "root" value compared to an array child. Given the data:
```php
$input = [
  'myObjs' => [
    ['myDate'=>'2018-01-01'],
    ['stuff'=>true]
  ]
];
$v = new Validator($input);
$v->rule('date', 'myObjs.*.myDate');
if (!$v->validate()) echo $v->errors(); # = Invalid date
```
Will say that `date` is invalid, as it is not present on the second object. While evaluating them individually it does not matter that `date` is missing (unless it's specified as required).
```php
$input = ['date'=>'2018-01-01'];
$v = new Validator($input);
$v->rule('date', 'myDate');
if (!$v->validate()) echo $v->errors(); # = All ok
```
Is this intentional?

**Comment by willemwollebrants** [comment]
Looks like a bug to me, I'll look into it
