### ISSUE TITLE
Differenciation between array and associativeArray

### ISSUE THREAD

**Issue by IvanDelsinne** [vlucas/valitron#265]
Is there any defined filter to precisely check for an *associative* array and not a simple array ?

**Comment by willemwollebrants** [comment]
I don't think so. AFAIK any array is treated as associative by php. You'll probably need a custom validator to check if the array only has numerical, sequential keys. Or if it's a small array, you can do something like
```php
if(array_values($arr) === $arr){ 
//...
}
```
