### ISSUE TITLE
Grabbing individual errors

### ISSUE THREAD

**Issue by Benjy1979** [vlucas/valitron#27]
Thanks for giving me an alternative to that awkward Respect/Validator thing. 

I know there is a function errors() in the Valitron library, can someone add a function to allow retrieval of the error string that represents one particular field.

I realise I can just do $v->errors() and get the index of the array. However I think it's cleaner for future dev to have a function that retrieves it to save breaking changes later on if you ever change the format of the errors. Even if that function is simply indexing the array for the time being.

Cheers.

**Comment by chrisbjr** [comment]
@vlucas how do you suggest we log the validation errors if the log is expecting strings?

**Comment by vlucas** [comment]
If you really want them in a string, you can just `implode` them together:

```php
$messageString = [];
foreach($v->errors() as $field => $messages) {
    $messageString[$field] = implode(', ', $messages);
}
```
