### ISSUE TITLE
URL validation doesnt work correct

### ISSUE THREAD

**Issue by juergenweb** [vlucas/valitron#274]
Checking the URL validation with PHP FILTER_VALIDATE_URL only let incorrect URLs to pass as valid.

Demo: 
`$url = "https://ww.w3schools.com";

if (filter_var($url, FILTER_VALIDATE_URL)) {
    echo("$url is a valid URL");
} else {
    echo("$url is not a valid URL");
}`

The entered URL is not correct because one 'w' is missing in this case, but the filter ignores this and outputs that this is a correct URL.  This is a problem of the PHP filter.

Maybe an additional Regex test could solve this problem.

Best regards Jürgen

**Comment by willemwollebrants** [comment]
While the FILTER_VALIDATE_URL does have its problems, 'https://ww.w3schools.com' has the format of a valid url. The people at w3schools.com (or anyone really) can have a ww. subdomain, after all.

If you want to make sure the url is valid AND actually exists, check out the urlActive rule.

**Comment by juergenweb** [comment]
OK Thanks for the information
