### ISSUE TITLE
Allowing date to be null / empty

### ISSUE THREAD

**Issue by adarshmadrecha** [vlucas/valitron#275]
I have a key `dtcomplete` which should be a valid date. However it can also be empty.

```
$v = new Valitron\Validator(array('dtcomplete'=>""));
$rules = [
    'required' => [['dtcomplete', true]],
    'date' => [['dtcomplete']]
];
$v->rules($rules);
$v->validate();
```

I was under impression based on the discussion #208 that if required is passed a second parameter as true, then empty or null value is allowed in the key.

**Comment by willemwollebrants** [comment]
The 'required' rule is not failing, but the 'date' rule is. This makes sense: an empty string is not a valid date. Not having the 'required' rule would make sure that Valitron doesn't try to validate empty fields, which sounds like what you need

**Comment by adarshmadrecha** [comment]
The key is always present and required to be present. Since I am getting the value in `$_POST` through the android app API call

**Comment by willemwollebrants** [comment]
The 'required' rule checks if the key exists: it does. 
The 'date' rule checks if the value is a valid date: it isn't.

You'll notice that `$v->errors()` will only have an error about the date
