### ISSUE TITLE
How to strip and remove redundant data (filter data)?

### ISSUE THREAD

**Issue by rvalitov** [vlucas/valitron#277]
Hi! Sometimes the input data may contain extra fields that are not required for further processing. In this case the validation passes for the fields marked as `required` and `optional`. I want to strip all other fields other than these marked from the input data after the successful validation. Does Valitron provides such functionality? Or what's the best approach to achieve that? Thank you!

**Comment by willemwollebrants** [comment]
It's not what Valitron is for really, but I guess you could use the second constructor parameter to tell Valitron which fields should be included in the data that's going to be validated and get that array by calling the data() method. 

(Personally, I'd just build a new array myself with the fields and values I need)
