### ISSUE TITLE
Optional value object with all fields required

### ISSUE THREAD

**Issue by apapsch** [vlucas/valitron#278]
A value object has no identity, thus all its fields make up the identity. Monetary values are an example (amount + currency) or address (name + street + city + country + any other address attribute). If the value object is optional in a parent object, it may either be omitted completely or all fields must be present. Additional validation rules on the individual fields may apply.

Valitron doesn't seem to support this use case yet with the built-in rules. I have cooked up the custom rule `value_object`. You can then specify `address` as optional, to satisfy the use case, like this (in my custom format):

```
"value_object": [
  ["address", ["title", "salutation", "name", "street", "zip", "city", "country"]]
],
"optional": [
  ["address"]
]
```

```
    public function isValid($field, $value, $params, $fields): bool
    {
        if (!is_array($params) || \count($params) === 0) {
            throw new \InvalidArgumentException('Required fields of value object ' . $field . ' not specified');
        }
        $requiredFields = $params[0];
        if (\count($requiredFields) === 0) {
            throw new \InvalidArgumentException('Required fields of value object ' . $field . ' are empty');
        }
        foreach ($requiredFields as $fieldName) {
            if (!array_key_exists($fieldName, $value)) {
                return false;
            }
        }
        return true;
    }
```

If the interest is there, I can integrate it properly into Valitron and send the PR. Rule name also must not necessarily be `value_object`. `required_fields` instead?

**Comment by willemwollebrants** [comment]
I think I get the concept, but I'm not a big fan of the name at first glance to be honest mainly because it validates arrays, not objects. 

From your code it looks like it checks if the address array has certain keys, so maybe it could become a different rule:

```php
$v->rule('optional','address');
$v->rule('arrayHasKeys', 'address', array('title', 'salutation', 'name', 'street'));
```

I think this would be very useful and that the name might be a bit clearer too. What do you think?

**Comment by apapsch** [comment]
Great, I'll send the PR soon with `arrayHasKeys` as the rule name.

**Comment by willemwollebrants** [comment]
merged, thanks a lot!
