### ISSUE TITLE
Incorrect callback typehint in phpdoc markup for rule method

### ISSUE THREAD

**Issue by auroraeosrose** [vlucas/valitron#281]
The rule registration still uses the invalid "callback" instead of "callable" as the phpdoc typehint which makes static analysis angry

I think this was already filed at one point but apparently didn't actually get merged?

https://github.com/vlucas/valitron/blob/master/src/Valitron/Validator.php#L1232

Turned off my psalm suppression and caught this :)

**Comment by willemwollebrants** [comment]
Thanks for letting me know :)
