### ISSUE TITLE
dateFormat doesn't seem to restrict input to the specified format in the expected way

### ISSUE THREAD

**Issue by bansheekitty** [vlucas/valitron#292]
I have a 'year' field and I'd like to require a four-digit year, so I used the dateFormat rule with the format 'Y'. However, the field accepts anywhere from 1-4 numbers as valid, so for example, just the number '1' in the field passes as valid. I've tried this with other formats as well, for example 'Y-m-d' which is the example used in the readme notes, accepts '1/1/1' as valid, although 'Y' refers to a four-digit year, 'm' refers to a two-digit month, and 'd' refers to a two digit day, assuming standard date formats such as listed here: https://www.php.net/manual/en/function.date.php

How can I require a four-digit year using dateFormat?

Thanks!

**Comment by willemwollebrants** [comment]
As far as php is concerned, 1/1/1 is a valid Y/m/d date for parsing dates. We use date_parse_from_format, but it also works with DateTime::createFromFormat:
```php
echo DateTime::createFromFormat('Y/m/d', '1/1/1')->format('Y/m/d');
//output 0001/01/01
```
If you require a date to be entered in the exact format (as opposed to a 'parseable format'), you're probably better off using the regex rule.
