### ISSUE TITLE
How can I validated a file

### ISSUE THREAD

**Issue by kabircse** [vlucas/valitron#297]
I have multiple images on my form. For validating file type, size:
I used the code as given below:

            $v = new Validator($_FILES);
            //make sure we have no error
            $v->rule('in', ['EmployeePhoto.error','EmployeeSignature.error'], [0])->message('No image selected for {field}');
            //check the mime type
            $v->rule('in', ['EmployeePhoto.type','EmployeeSignature.type'], ['image/jpeg'])->message('Only jpg image is allowed for {field}.');
            //check maximum file size
            $v->rule('in', ['EmployeePhoto.size','EmployeeSignature.size'], [1000])->message('Image size must be less than 1Mb for {field}.');

Problem:
        1. Validated if the image exists, but it always validating image if not attest. 
        2. Image max size can not be validating, Also I tried 'max' instead of 'in'

Is there any solution?

**Comment by vlucas** [comment]
Valitron does not natively handle or parse image information. You will have to do that yourself, and then use the validator. You might also have to loop over all the files in `$_FILES` and add the validation rules for each inside the loop, with the specific properties for that file.

**Comment by willemwollebrants** [comment]
See my comments at #157 for more info about validating file properties
