### ISSUE TITLE
Validate combination of fields, one should be filled (different)

### ISSUE THREAD

**Issue by bjornpost** [vlucas/valitron#30]
Given:

```
$v = new \Valitron\Validator(array('foo' => '', 'bar' => '')); 
$v->rule('different', 'foo', 'bar');
$v->validate(); // true
```

That doesn't seem correct to me; foo and bar are not different at all. In my case either foo or bar should be filled, but if both are empty, validation should fail.

I guess this is caused by #14. I can't require both fields; as foo is only required when bar is empty, and vice versa.

**Comment by it-all** [comment]
Custom function?
