### ISSUE TITLE
Negative int value always passes 'integer' rule

### ISSUE THREAD

**Issue by kostamilorava** [vlucas/valitron#302]
```
@$v = new Valitron\Validator(['alias' => '-555']);
$v->rules([
	'integer' => [
		['alias']
		]
	]);
$v->validate()
```
Validation always returns true. It's negative value, so without true in alias array it must return false.

**Comment by willemwollebrants** [comment]
An integer can be negative: [https://www.php.net/manual/en/language.types.integer.php](https://www.php.net/manual/en/language.types.integer.php)

**Comment by kostamilorava** [comment]
It can be negative, but in valitron's documentation it says, you must select true to pass validation! It always passes with or without true. I can't filter integer for negative value.

![image](https://user-images.githubusercontent.com/45169743/71409938-bc868280-265c-11ea-8b5b-1db78edc97e8.png)

**Comment by willemwollebrants** [comment]
Hm you're absolutely right 😳
I'm a bit torn: I can see why you'd only want 0 or positive integers in some cases, but that's not what an integer actually is. I'm going to try and find if/when the behavior has changed and I'll get back to you

**Comment by willemwollebrants** [comment]
The documentation was off (probably a misunderstanding), so I fixed the documentation :)
