### ISSUE TITLE
Valitron failed to detect this kind of email "-myemail@mydomain.com" as invalid email

### ISSUE THREAD

**Issue by hendrowicaksono** [vlucas/valitron#318]
Valitron failed to detect this kind of email "-myemail@mydomain.com" as invalid email. Instead it is detected as valid email format by valitron.

**Comment by willemwollebrants** [comment]
We use FILTER_VALIDATE_EMAIL ([https://www.php.net/manual/en/filter.filters.validate.php](https://www.php.net/manual/en/filter.filters.validate.php)) which is not 100% perfect, but it's pretty well documented and predictable for most php devs

Side note: I tested that e-mail with a bunch of e-mail validation services and most of them make no problem of the format. I think it actually has the valid format, but not all e-mail servers will resolve it.
