### ISSUE TITLE
PHP8?

### ISSUE THREAD

**Issue by omexlu** [vlucas/valitron#326]
Hello,

I wanted to ask if the current version is compatible with PHP8 and if not for when that is expected to be the case?

Thanks in advance.

**Comment by willemwollebrants** [comment]
The latest release is tested with PHP 8.0 and seems to work without any modifications to the code (some modifications in the tests were needed but nothing functional)

**Comment by omexlu** [comment]
opened this issue on 14 Dec 2020

Nice Reaction time...

**Comment by willemwollebrants** [comment]
Thank you for making my life easier and letting me know I can just close any issue you file without looking at it.
