### ISSUE TITLE
Boolean for empty fields usage

### ISSUE THREAD

**Issue by 2ik** [vlucas/valitron#333]
Hello,

Thanks for this library)

Is it possible to enable validation for empty fields?

```php
$v = new \Valitron\Validator(['remember_me' => null]); // null, ""
$v->rules([
    'boolean' => [
        ['remember_me']
    ]
]);
$v->validate(); // true,  expected: false
```
Thanks

**Comment by willemwollebrants** [comment]
Hi 2ik, Valitron does not run any validations on empty fields, unless the field is required. If a field is not required, this means that an empty value is acceptable. If an empty value is not acceptable, the field is required. 
What you want is to mark the field as being required (a non-empty value must be present) AND it must be boolean:
```php
$v->rules([
    'required' => [
        ['remember_me']
    ],
    'boolean' => [
        ['remember_me']
    ]
]);
```
