### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by ghost** [vlucas/valitron#357]
In php 8.1 php functions will crash passing null instead of an string.

For example:

```
$rules = [
                'required' => [
                    'source',
                ],
                'url' => [
                    'source',
                ],
            ];
```

`strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/vlucas/valitron/src/Valitron/Validator.php line 655`

Acceted
* strpos
* *trim 
* I guess all other that require typed string value

# Workaround
```php
error_reporting(E_ALL & ~E_DEPRECATED);
```

**Comment by Tautve** [comment]
@galdp I'll fix this
