### ISSUE TITLE
Do you need help ?

### ISSUE THREAD

**Issue by dfranco** [vlucas/valitron#373]
Hi @vlucas ,

I'm glad to say that I've started to valitron within few of my projects and it works really great.

In the same time, I see several pending pull requests and several issues without any feedbacks.

I know it could be difficult to handle pro, private life + maintaining an oss project like yours (I'm in the same situation).

So to keep it simple, if you need and would like to get some help from the community, I'll be glad to help.

Best,

**Comment by vlucas** [comment]
Awesome @dfranco. I would love some help on this. Can you email me at vance [at] vancelucas [dot] com?

**Comment by dfranco** [comment]
> Awesome @dfranco. I would love some help on this. Can you email me at vance [at] vancelucas [dot] com?

Sure
