### ISSUE TITLE
RequiredWith

### ISSUE THREAD

**Issue by dikaso** [vlucas/valitron#75]
Title says it all.

How would you implement this?

**Comment by ellotheth** [comment]
@DinkoMiletic probably means something like this:

```{php}
protected function validateRequiredWith($field, $value, array $params) {
    list($match, $child) = $params;
    if ($value == $match) {
        return array_key_exists($child, $this->_fields) && $this->validateRequired($child, $this->_fields[$child]);
    }
    
    return true;
}
```
When `$value` is `$match`, `$child` is required.
```{php}
$v = new Validator($post);
$v->rule('requiredWith', 'type', '2', 'second-field);
```
It'd be useful if you have a form field with multiple possible values (maybe a set of checkboxes), one of which requires extra information (maybe a text field has to be filled out if one of the checkboxes is selected).

The rest of the logic gets a little hinkey (e.g. `hasRule()`, the initial `validate()` check for `required`, nested fields, etc.), but I think that's the gist.

**Comment by mangopeaches** [comment]
https://github.com/vlucas/valitron/pull/267 should take care of this
