### ISSUE TITLE
Array Validation 

### ISSUE THREAD

**Issue by Petah** [vlucas/valitron#8]
How would you do array validation?

Say I have this input:

```
$_POST = [
    'users' => [
        7 => 'user@site.com',
        12 => 'anotheruser@site.com',
    ]
];
```

I want to validate that the `users` key exists in `$_POST`, and its value is an array.

Then for each key of the users array, I want to validate the key is a user ID (callback).

Then for each value of the users array, I want to validate that the value is an email address.

Is this possible with this library? If so, how?

**Comment by nikosv** [comment]
How do i get an error for a specific field in this case?

**Comment by thinkjson** [comment]
What do you mean? Can you provide example code?

**Comment by nikosv** [comment]
Ok. Let's take the following as an example.
```
$v = new Valitron\Validator(array('settings' => array(
    array('threshold' => 50),
    array('threshold' => 90)
)));
$v->rule('max', 'settings.*.threshold', 80);
if($v->validate()) {
    echo "Yay! We're all good!";
} else {
    // Errors
    print_r($v->errors());
}
```
The field that failed validation is the second one. But how can i get this information?
Is there a way to get the index of the settings array that failed validation?

**Comment by thinkjson** [comment]
If you don't want all or nothing validation, then iterate over the array (settings in this example) and build up an array of errors. For example:

	$data = array('settings' => array(
	    array('threshold' => 50),
	    array('threshold' => 90)
	));

	$errors = [];
	foreach ($data['settings'] as $setting) {
		$v = new Valitron\Validator($setting);
		$v->rule('max', 'threshold', 80);
		if($v->validate()) {
		    $errors[] = null;
		} else {
		    $errors[] = $v->errors();
		}
	}

	var_dump($errors);

**Comment by nikosv** [comment]
Ok! This is definetely a solution. Although i feel the loop should be part of Valitron's default array validation functionallity.

Thanks @thinkjson

**Comment by thinkjson** [comment]
What would the output look like?

**Comment by nikosv** [comment]
Well i guess the $v->errors() output in case of an array validation could be something like 
```
Array ( [grades.{array_index}] => Array ( [0] => Grades.{array_index} mplah mpah mplah validation error ) )
```
instead of
```
Array ( [grades.*] => Array ( [0] => Grades.* mplah mpah mplah validation error ) )
```
which provides no info about the field that failed validation

**Comment by thinkjson** [comment]
So you would use string parsing to determine which element in the array
failed?

**Comment by nikosv** [comment]
Parse the string? well not exactly. In my case i just wanted to be able to do some UI related actions per input field (red border and error message on specific input that failed validation) like so:
```
if($v->errors("grades.$row->id")) {
    $class= 'has-error';
    $error = $v->errors('grades.$row->id')[0];
}
```
It just doesn't seem right to me that Valitron treats array input as single input as regards to errors. I believe that errors should always be bound to specific input. In addition to my previous answer error output could also be something like
```
Array ( [grades] => 
        Array ( [{input_array_index}] => 
                  Array ( [{error_index}] => Grades.* mplah mpah mplah validation error )
        )
)
```

**Comment by Petah** [comment]
Just a note, Symfony Validator supports this use case.

**Comment by filozofer** [comment]
Here's a very basic example for apply validation rules on a simple array:

`$v->rule('email', ['recipients.*']);`

20 minutes search for this line, I think it deserve to be in the documentation in the example code after "You may use dot syntax to access members of multi-dimensional arrays, and an asterisk to validate each member of an array:"
