### ISSUE TITLE
Custom validation rules and access to other fields values

### ISSUE THREAD

**Issue by idrarig** [vlucas/valitron#87]
Sometimes when you want to validate a field `first` you need to look at another field, `second`.  That's the case when you are comparing two password fields for instance, and for that you would use the builting `equals` validator.  But what if you need such functionality in a custom validation rule that you add using the static method `addRule()`?  At the moment it is not possible.

Perhaps it would be possible to pass a read-only version of the protected `$_fields` property of `Validator` to the callback used in `addRule()`.

Of course this is a non-issue if one is okay with just extending the `Validator` class and adding validation methods to it.

**Comment by chrisvanpatten** [comment]
An extra parameter on the `addRule()` callback would be awesome!
