### ISSUE TITLE
Dealing with "pseudo-optional" form fields

### ISSUE THREAD

**Issue by alexweissman** [vlucas/valitron#90]
I love the concept of this project, and I'm looking to integrate this with one of my current projects (https://github.com/alexweissman/UserFrosting).  Right now, our validation rules are hardcoded, repetitive `if-else` statements all over our codebase.  This would help clean it up nicely.

I was wondering, do you have any recommendations for how to deal with "pseudo-optional" HTML form fields such as checkboxes?  I.e., fields which aren't really "optional", but whose absence is interpreted as `false` and presence as `true`?  Right now we're using the `isset` function, but I wonder if there is a more elegant way using Valitron.

**Comment by willemwollebrants** [comment]
Maybe if we ever do a valitron/filter package :)
