### ISSUE TITLE
Set the checkAndSetLabel() as protected

### ISSUE THREAD

**Issue by wingsline** [vlucas/valitron#96]
Is it possible to set the checkAndSetLabel() as protected?
When I want to extend the class with custom error() function cannot because the checkAndSetLabel() is private.
Thanks.

**Comment by willemwollebrants** [comment]
Sorry this took so long:

since checkAndSetLabel affectes $_labels[], which is "protected" I don't see a good reason why checkAndSetLabel should be private.

So consider it protected now :)
